version: '3'

services:
  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    ports:
      - "1880:1880"  
    volumes:
      - ./data:/data
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - nodered-network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"  
    volumes:
      - ./influxdb-data:/var/lib/influxdb 
    environment:
      - INFLUXDB_DB=mydb 
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    networks:
      - nodered-network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"  
      - "9001:9001" 
    volumes:
      - ./mosquitto-data:/mosquitto/data  
      - ./mosquitto-config:/mosquitto/config 
    networks:
      - nodered-network

networks:
  nodered-network:
    driver: bridge
